BiraFit/Controllers/BedarfController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BiraFit.Models;
using BiraFit.Controllers.Helpers;
using Microsoft.AspNet.Identity;
using BiraFit.ViewModel;

namespace BiraFit.Controllers
{
    public class BedarfController : BaseController
    {
        //
        // GET: /Bedarf/Index
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /Bedarf/New
        public ActionResult New()
        {
            if (IsSportler())
            {
                var sportlerId = GetAspNetSpecificIdFromUserId(User.Identity.GetUserId());
                if (IsBedarfOpen(sportlerId))
                {
                    return RedirectToAction("Index", "Home");
                }
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        //
        // POST: /Bedarf/New
        [HttpPost]
        public ActionResult New(BedarfCreateViewModel model)
        {
            if(ModelState.IsValid)
            {
                Context.Bedarf.Add(new Bedarf()
                {
                    Titel = model.Titel,
                    Beschreibung = model.Beschreibung,
                    Preis = model.Preis,
                    Ort = model.Ort,
                    OpenBedarf = true,
                    Sportler_Id = GetAspNetSpecificIdFromUserId(User.Identity.GetUserId()),
                    Datum = DateTime.Now
                });
                Context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }         
            return View(model);
        }

        //
        // GET: /Bedarf/Edit/1
        public ActionResult Edit(int id)
        {
            var sportlerId = GetAspNetSpecificIdFromUserId(User.Identity.GetUserId());

            if (IsBedarfOwner(id, sportlerId))
            {
                var bedarf = Context.Bedarf.Single(b => b.Id == id);
                BedarfEditViewModel bedarfViewModel = new BedarfEditViewModel()
                {
                    Id=id,
                    Titel=bedarf.Titel,
                    Beschreibung=bedarf.Beschreibung,
                    Datum=bedarf.Datum,
                    OpenBedarf=bedarf.OpenBedarf,
                    Ort=bedarf.Ort,
                    Preis=bedarf.Preis            
                };
                return View(bedarfViewModel);
            }

            return HttpNotFound();
        }

        //
        // POST: /Bedarf/Delete/1
        public ActionResult Delete(int id)
        {
            if (IsSportler())
            {
                var bedarf = Context.Bedarf.Single(i => i.Id == id);

                if (GetAspNetUserIdFromSportlerId(bedarf.Sportler_Id) == User.Identity.GetUserId())
                {
                    DeleteOpenAngebote(bedarf.Id);
                    Context.Bedarf.Remove(bedarf);
                    Context.SaveChanges();
                }
            }
            return RedirectToAction("Index", "Home");
        }

        private void DeleteOpenAngebote(int bedarfId)
        {
            if(Context.Angebot.Any(s => s.Bedarf_Id == bedarfId))
            {
                var openAngebote = Context.Angebot.Where((s => s.Bedarf_Id == bedarfId));
                Context.Angebot.RemoveRange(openAngebote);
            }
        }

        //
        // POST: /Bedarf/Edit/1
        [HttpPost]
        public ActionResult Edit(BedarfEditViewModel bedarf)
        {
            if (IsSportler() && ModelState.IsValid)
            {
                var sportlerId = GetAspNetSpecificIdFromUserId(User.Identity.GetUserId());
                var bedarfInDb = Context.Bedarf.FirstOrDefault(b => b.Sportler_Id == sportlerId && b.OpenBedarf);
                bedarfInDb.Datum = DateTime.Now;
                TryUpdateModel(bedarfInDb);
                Context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(bedarf);

        }

        private bool IsBedarfOpen(int sportlerId)
        {
            return Context.Bedarf.Any(b => b.Sportler_Id == sportlerId
                                           && b.OpenBedarf);
        }

        private bool IsBedarfOwner(int bedarfId, int sportlerId)
        {
            return Context.Bedarf.Any(b => b.Id == bedarfId &&
                                           b.Sportler_Id == sportlerId);
        }

        [ChildActionOnly]
        public ActionResult BedarfNavigation()
        {
            if (IsSportler())
            {
                ViewBag.Type = "Sportler";
                var sportlerId = GetAspNetSpecificIdFromUserId(User.Identity.GetUserId());
                if (IsBedarfOpen(sportlerId))
                {
                    ViewBag.Id = Context.Bedarf.Single(b => b.Sportler_Id == sportlerId).Id;
                }
            }
           
            return PartialView();
        }
    }
}

BiraFit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="/Content/bootstrap.css" rel="stylesheet">
    <link href="/Content/site.css" rel="stylesheet">
    <link href="/Content/star-rating.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>  
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/star-rating")
    <link rel="shortcut icon" href="~/favicon2.ico" />
    <link rel="icon" href="~/favicon2.ico" type="image/ico" />
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="menuBar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" id="myBurgerButton" class="navbar-toggle" data-toggle="collapse" data-target="#navbarDidCollapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar" id="burgerLine"></span>
                    <span class="icon-bar" id="burgerLine"></span>
                    <span class="icon-bar" id="burgerLine"></span>
                </button>
                <h1 class="modal-title"><a id="titleLink" href="/">BiraFit</a></h1>
            </div>
            <div class="collapse navbar-collapse" id="navbarDidCollapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>





        <div class="container body-content">
            @RenderBody()
            <footer id="footer">
                <p>&copy; @DateTime.Now.Year - BiraFit</p>
                <p>Kontakt: <a href="birafit17@gmail.com" id="link">birafit17@gmail.com</a></p>
            </footer>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

BiraFit/Views/Shared/angebotNavigation.cshtml
 @if (ViewBag.Type == "Sportler")
 {
    <li>@Html.ActionLink("Alle Angebote", "Index", "Angebot", routeValues: null, htmlAttributes: new { id = "navlink" })</li>
 }
 else
 {
    <li>@Html.ActionLink("Meine Angebote", "AngebotTrainer", "Angebot", routeValues: null, htmlAttributes: new { id = "navlink" })</li>
 }

BiraFit/Views/Shared/bedarfNavigation.cshtml
@{ 
    var path = "Edit/" + ViewBag.id;
}

@if (ViewBag.Type == "Sportler")
{
    if (ViewBag.Id != null)
    {
        <li>@Html.ActionLink("Bedarf anpassen", (string)path, "Bedarf", routeValues: null, htmlAttributes: new { id = "navlink" })</li>
    }
    else
    {
        <li>@Html.ActionLink("Neuen Bedarf", "New", "Bedarf", routeValues: null, htmlAttributes: new { id = "navlink" })</li>
    }
}